apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: uptime-guardian
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/name: uptime-guardian
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
