apiVersion: v1
kind: Service
metadata:
  name: {{ include "uptime-guardian.fullname" . }}
  labels:
    {{- include "uptime-guardian.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "uptime-guardian.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
