apiVersion: v1
kind: Service
metadata:
  name: uptime-guardian
  labels:
    app: uptime-guardian
spec:
  type: NodePort
  selector:
    app: uptime-guardian
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
